### ISSUE TITLE
System.OutOfMemoryException when generating excel with SAX from very large sql result

### ISSUE THREAD

**Issue by swidz** [swidz/Sql2Xls#6]
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.IO.MemoryStream.set_Capacity(Int32 value)
   at System.IO.MemoryStream.EnsureCapacity(Int32 value)
   at System.IO.MemoryStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at System.Xml.XmlUtf8RawTextWriter.FlushBuffer()
   at System.Xml.XmlUtf8RawTextWriter.WriteAttributeTextBlock(Char* pSrc, Char* pSrcEnd)
   at System.Xml.XmlUtf8RawTextWriter.WriteString(String text)
   at System.Xml.XmlWellFormedWriter.WriteString(String text)
   at DocumentFormat.OpenXml.OpenXmlPartWriter.WriteStartElement(OpenXmlElement elementObject, IEnumerable`1 attributes, IEnumerable`1 namespaceDeclarations)
   at Sql2Xls.Excel.Adapters.ExcelExportSAXAdapter.CreateSharedStringCellSAX(OpenXmlWriter openXmlWriter, Int32 columnIndex, Int32 rowIndex, String value, UInt32 styleIndex, Boolean isValueSharedString) in D:\projects\Sql2Xls\src\Sql2Xls\Excel\Adapters\ExcelExportSAXAdapter.cs:line 422
   at Sql2Xls.Excel.Adapters.ExcelExportSAXAdapter.CreateSheetDataSAX(OpenXmlWriter openXmlWriter, DataTable dataTable) in D:\projects\Sql2Xls\src\Sql2Xls\Excel\Adapters\ExcelExportSAXAdapter.cs:line 333
   at Sql2Xls.Excel.Adapters.ExcelExportSAXAdapter.CreateWorksheet(SpreadsheetDocument document, WorksheetPart worksheetPart, DataTable dataTable) in D:\projects\Sql2Xls\src\Sql2Xls\Excel\Adapters\ExcelExportSAXAdapter.cs:line 298
   at Sql2Xls.Excel.Adapters.ExcelExportAdapter.CreateFromDataTable(SpreadsheetDocument document, DataTable dataTable) in D:\projects\Sql2Xls\src\Sql2Xls\Excel\Adapters\ExcelExportAdapter.cs:line 204
   at Sql2Xls.Excel.Adapters.ExcelExportAdapter.LoadFromDataTable(DataTable dataTable) in D:\projects\Sql2Xls\src\Sql2Xls\Excel\Adapters\ExcelExportAdapter.cs:line 96
   at Sql2Xls.Sql2XlsService.CreateDocument(String datasetName, String sqlCommand, String outputFile, Sql2XlsServiceParameters parms) in D:\projects\Sql2Xls\src\Sql2Xls\Sql2XlsService.cs:line 181
   at Sql2Xls.Sql2XlsService.ProcessTask(Sql2XlsTaskData taskData, Sql2XlsServiceParameters parms) in D:\projects\Sql2Xls\src\Sql2Xls\Sql2XlsService.cs:line 135

**Comment by swidz** [comment]
https://github.com/dotnet/runtime/issues/23750

https://github.com/dotnet/Open-XML-SDK/issues/807

**Comment by swidz** [comment]
Unit test added
